### ISSUE TITLE
Support multi-level variables

### ISSUE THREAD

**Issue by mauriciofierrom** [mauriciofierrom/ansible-vault-nvim#1]
Current implementation only supports top-level variables:

```yaml
var: vault! |
  ...
```

We need to support multi-level variables:

```yaml
vars: # for some reason
  nested1: !vault |
    ...
  nested2:
     moar_nesting: !vault |
       ...
```
