### ISSUE TITLE
Encrypted content doesn't conform to literal style

### ISSUE THREAD

**Issue by mauriciofierrom** [mauriciofierrom/ansible-vault-nvim#6]
After encrypting a variable the multi-line encrypted content doesn't follow the [literal style for block scalars](https://yaml.org/spec/1.2/spec.html#id2795688):

Before:
```yaml
level-1:
  sublevel-1:
    var-1: value
    unencrypted-value: value
```

After:
```yaml
level-1:
  sublevel-1:
    var-1: value
    unencrypted-value: !vault |
    -------------------------------------
    -------------------------------------
    -------------------------------------
```

Where the dashes are the `$ANSIBLE_VAULT` block. This (naturally) causes parsing errors.

The YAML Specification states that [only spaces are considered for indentation](https://yaml.org/spec/1.2/spec.html#id2777534).
